version: "3"
services:
  php:
    build:
      context: ./env/services/${PHPVERSION}
    container_name: '${APP_NAME}-${PHPVERSION}'
    restart: unless-stopped
    expose:
      - "${PHP_PORT}"
    tty: true
    links:
      - database
    volumes:
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${PHP_XDEBUGGER}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  webserver:
    build:
      context: ./env/services/${WEBSERVER}
    container_name: webserver
    restart: always
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${WEBSERVER_CONFIG}:/etc/nginx/conf.d
    depends_on:
      - php

  database:
    build:
      context: "./env/services/${DATABASE}"
    container_name: '${APP_NAME}-database'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_DATABASE_SOCKET}:3306"
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/mysql
      - ${DATABASE_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
